/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtRouteRouteImport } from './routes/tt/route'
import { Route as QuizRouteRouteImport } from './routes/quiz/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as TtPlayRouteImport } from './routes/tt/play'
import { Route as TtCreateRouteImport } from './routes/tt/create'
import { Route as TtActivitiesRouteImport } from './routes/tt/activities'
import { Route as QuizResultsRouteImport } from './routes/quiz/results'
import { Route as IngestSplatRouteImport } from './routes/ingest.$'

const TtRouteRoute = TtRouteRouteImport.update({
  id: '/tt',
  path: '/tt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRouteRoute = QuizRouteRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRouteRoute,
} as any)
const TtPlayRoute = TtPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => TtRouteRoute,
} as any)
const TtCreateRoute = TtCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TtRouteRoute,
} as any)
const TtActivitiesRoute = TtActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => TtRouteRoute,
} as any)
const QuizResultsRoute = QuizResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizRouteRoute,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/tt': typeof TtRouteRouteWithChildren
  '/ingest/$': typeof IngestSplatRoute
  '/quiz/results': typeof QuizResultsRoute
  '/tt/activities': typeof TtActivitiesRoute
  '/tt/create': typeof TtCreateRoute
  '/tt/play': typeof TtPlayRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tt': typeof TtRouteRouteWithChildren
  '/ingest/$': typeof IngestSplatRoute
  '/quiz/results': typeof QuizResultsRoute
  '/tt/activities': typeof TtActivitiesRoute
  '/tt/create': typeof TtCreateRoute
  '/tt/play': typeof TtPlayRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/tt': typeof TtRouteRouteWithChildren
  '/ingest/$': typeof IngestSplatRoute
  '/quiz/results': typeof QuizResultsRoute
  '/tt/activities': typeof TtActivitiesRoute
  '/tt/create': typeof TtCreateRoute
  '/tt/play': typeof TtPlayRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz'
    | '/tt'
    | '/ingest/$'
    | '/quiz/results'
    | '/tt/activities'
    | '/tt/create'
    | '/tt/play'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tt'
    | '/ingest/$'
    | '/quiz/results'
    | '/tt/activities'
    | '/tt/create'
    | '/tt/play'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/tt'
    | '/ingest/$'
    | '/quiz/results'
    | '/tt/activities'
    | '/tt/create'
    | '/tt/play'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRouteRoute: typeof QuizRouteRouteWithChildren
  TtRouteRoute: typeof TtRouteRouteWithChildren
  IngestSplatRoute: typeof IngestSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tt': {
      id: '/tt'
      path: '/tt'
      fullPath: '/tt'
      preLoaderRoute: typeof TtRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/tt/play': {
      id: '/tt/play'
      path: '/play'
      fullPath: '/tt/play'
      preLoaderRoute: typeof TtPlayRouteImport
      parentRoute: typeof TtRouteRoute
    }
    '/tt/create': {
      id: '/tt/create'
      path: '/create'
      fullPath: '/tt/create'
      preLoaderRoute: typeof TtCreateRouteImport
      parentRoute: typeof TtRouteRoute
    }
    '/tt/activities': {
      id: '/tt/activities'
      path: '/activities'
      fullPath: '/tt/activities'
      preLoaderRoute: typeof TtActivitiesRouteImport
      parentRoute: typeof TtRouteRoute
    }
    '/quiz/results': {
      id: '/quiz/results'
      path: '/results'
      fullPath: '/quiz/results'
      preLoaderRoute: typeof QuizResultsRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuizRouteRouteChildren {
  QuizResultsRoute: typeof QuizResultsRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteRouteChildren: QuizRouteRouteChildren = {
  QuizResultsRoute: QuizResultsRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteRouteWithChildren = QuizRouteRoute._addFileChildren(
  QuizRouteRouteChildren,
)

interface TtRouteRouteChildren {
  TtActivitiesRoute: typeof TtActivitiesRoute
  TtCreateRoute: typeof TtCreateRoute
  TtPlayRoute: typeof TtPlayRoute
}

const TtRouteRouteChildren: TtRouteRouteChildren = {
  TtActivitiesRoute: TtActivitiesRoute,
  TtCreateRoute: TtCreateRoute,
  TtPlayRoute: TtPlayRoute,
}

const TtRouteRouteWithChildren =
  TtRouteRoute._addFileChildren(TtRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRouteRoute: QuizRouteRouteWithChildren,
  TtRouteRoute: TtRouteRouteWithChildren,
  IngestSplatRoute: IngestSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
